# Generated by Django 5.2 on 2025-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='detailsUrl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='detailsUrl'),
        ),
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='placeId'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
