# Generated by Django 5.2 on 2025-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_detailsurl_place_placeid_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='detailsUrl',
            field=models.CharField(blank=True, default='/static/places/details-placeholder.json', max_length=200, null=True, verbose_name='detailsUrl'),
        ),
    ]
