# Generated by Django 4.2.20 on 2025-04-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='detailsUrl',
        ),
        migrations.RemoveField(
            model_name='place',
            name='placeId',
        ),
    ]
